// LOCALHOST
### Get all contacts
GET http://localhost:8080/contacts/
### Get contact by id GET
GET http://localhost:8080/contacts/63bf1d1d1f59f2630f964b6f 
### Create contact
POST http://localhost:8080/contacts/ HTTP/1.1
content-type: application/json 

{
    "firstName": "Nicholas",
    "lastName": "Leavitt",
    "birthday": "December 13",
    "email": "nicholas.r.leavitt@gmail.com",
    "favoriteColor": "Blue"
}
### PUT contact
PUT http://localhost:8080/contacts/63cc9f74a346c30d3845e359 HTTP/1.1
content-type: application/json

{
    "firstName": "Nathan",
    "lastName": "Cook",
    "birthday": "October 31",
    "email": "Nathancook648@gmail.com",
    "favoriteColor": "Orange"
}
### DELETE contact
DELETE http://localhost:8080/contacts/63cc9f74a346c30d3845e359 HTTP/1.1
###

// Render
### Get all contacts
GET http://chrisleavitt3.onrender.com/contacts
### Get contact by id GET
GET  http://chrisleavitt3.onrender.com/contacts/63bf1d1d1f59f2630f964b6f
### Create contact
POST http://chrisleavitt3.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Nicholas",
    "lastName": "Leavitt",
    "birthday": "December 13",
    "email": "nicholas.r.leavitt@gmail.com",
    "favoriteColor": "Blue"
}
### PUT contact
PUT http://chrisleavitt3.onrender.com/contacts/63cca069202125aa15d02951 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Nathan",
    "lastName": "Cook",
    "birthday": "October 31",
    "email": "Nathancook648@gmail.com",
    "favoriteColor": "Orange"
}
### DELETE contact
DELETE http://chrisleavitt3.onrender.com/contacts/63cca069202125aa15d02951 HTTP/1.1
###